apiVersion: apps/v1
kind: StatefulSet
metadata:
  # This name uniquely identifies the Deployment
  name: minio-deployment
  labels:
    app: minio 
spec:
  selector:
    matchLabels:
      app: minio
  serviceName: minio-service
  replicas: 5    
  template:
    metadata:
      labels:
        # Label is used as selector in the service.
        app: minio
    spec:
      containers:
      - name: minio
        # Pulls the default Minio image from Docker Hub
        image: minio/minio
        args:
        - server
        - /storage1
        env:
        # Minio access key and secret key
        - name: MINIO_ACCESS_KEY
          value: "minio"
        - name: MINIO_SECRET_KEY
          value: "minio123"
        ports:
        - containerPort: 9000
        # Mount the volume into the pod
        volumeMounts:
        - name: storage1 # must match the volume name, above
          mountPath: "/storage1"

  volumeClaimTemplates:
  - metadata:
      name: storage1
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
      storageClassName: gp2
---
apiVersion: v1
kind: Service
metadata:
  name: minio-service
  labels:
    app: minio
spec:
  ports:
    - port: 9000
      nodePort: 30397
      protocol: TCP
  selector:
    app: minio
  sessionAffinity: None
  type: NodePort
